### ISSUE TITLE
FriendlyCaptcha_Plugin is missing

### ISSUE THREAD

**Issue by Tobi7889** [slimco/formidable-field-frcaptcha#1]
It does not work, i can select the form field in Form Generator and add it.

After adding and save, it show the 
Friendly Captcha Headline in form.

If i submit the Message i get error:
FriendlyCaptcha_Plugin is missing

**Comment by slimco** [comment]
You need install plgun FriendlyCaptcha too https://sk.wordpress.org/plugins/friendly-captcha/ and set it. This is only bridge between this plugins.

**Comment by Tobi7889** [comment]
Plugin is already installed and site/api key in friendlycaptcha is configured. 
On Login/Register Form it works fine.

**Comment by Tobi7889** [comment]
Problem found:
In Settings of FriendlyCaptcha Plugins, nothing was enabled.
Your Addon only work, if some option is activated :)
